# Generated by Django 2.2.3 on 2019-07-13 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190711_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_create_update_destroy', 'Create, update and destroy data'),)},
        ),
    ]
